### ISSUE TITLE
Auto play

### ISSUE THREAD

**Issue by briancrandall** [individual11/colors#1]
Would be nice if the site auto-played from one song to the next, with perhaps 1 or 2 sec between.

**Comment by briancrandall** [comment]
And at the end it could simply go back to 1, or pop you back out to the landing page. Thoughts? Or play it all again backwards? :)

**Comment by individual11** [comment]
Ya, would wrap it around I think like the nav works now.

**Comment by individual11** [comment]
ok, should be working now
