### ISSUE TITLE
Polygon nav

### ISSUE THREAD

**Issue by briancrandall** [individual11/colors#2]
Could use polygons as next/previous nav. The number of sides on the polygon corresponds to the number of the next/previous track. For example, if I'm listening to track 5 and I mouse over to the right side of the screen, a hexagon filled with the 6th track's color slides out. If I click it, playback advances to track 6.

**Comment by briancrandall** [comment]
![image](https://f.cloud.github.com/assets/4105379/513917/469b716e-be4b-11e2-9e4d-6f24ddf9b892.png)

**Comment by briancrandall** [comment]
Could use circle for track 1. Need to find two-sided polygon. :)

**Comment by individual11** [comment]
ha, 2 sided polygon is a line, but won't be able to click on it.

**Comment by briancrandall** [comment]
Right. Tough to click on something that's purely theoretical. Though maybe for our next project... :) 

Probably just use two small circles.

**Comment by briancrandall** [comment]
New thought, since I seem bound and determined to make something clever of the prev/next.

![image](https://f.cloud.github.com/assets/4105379/579017/45fb4514-c868-11e2-9f08-0ac6cc0eddf7.png)

**Comment by briancrandall** [comment]
![image](https://f.cloud.github.com/assets/4105379/579019/55f7d8ba-c868-11e2-9efa-70fe160dea69.png)

![image](https://f.cloud.github.com/assets/4105379/579020/60ed1fbe-c868-11e2-9d1f-9c0491bcdfc0.png)

![image](https://f.cloud.github.com/assets/4105379/579022/6d8a55c0-c868-11e2-9783-d374f824ce7d.png)

![image](https://f.cloud.github.com/assets/4105379/579025/7ab81fa2-c868-11e2-8269-c12cba0d1a8a.png)

![image](https://f.cloud.github.com/assets/4105379/579027/8919a304-c868-11e2-9803-51d291581104.png)

![image](https://f.cloud.github.com/assets/4105379/579029/959b1cac-c868-11e2-99dd-10db3ceebcc9.png)

![image](https://f.cloud.github.com/assets/4105379/579035/a886c80c-c868-11e2-992f-970087409bc3.png)

![image](https://f.cloud.github.com/assets/4105379/579036/b17f3cc8-c868-11e2-961c-407c35c5002e.png)

**Comment by briancrandall** [comment]
aww c'mon! it's adorable! right?!
