### ISSUE TITLE
Share

### ISSUE THREAD

**Issue by briancrandall** [individual11/colors#3]
I'd like to make each individual track shareable/postable as well as the entire site. Thoughts on how to indicate that? I like that the experience is wordless, save for the landing page.

**Comment by individual11** [comment]
WIll need to incorporate Sammy.js to accomplish this personally. Are we adding share buttons, or copy/paste from the url?

**Comment by briancrandall** [comment]
Good question. Will the URL change as the tracks change? (I would guess not...) I'll give some thought to an icon solve, maybe when you mouse north?

**Comment by individual11** [comment]
Actually, the URL would change each time the track changes automatically using a hast http://colorminites.com/#/song1 as an example

**Comment by briancrandall** [comment]
here are the pngs you need!

![share colorminutes](https://f.cloud.github.com/assets/4105379/587379/afb57f72-c964-11e2-8e70-a8d8a90e1a92.png)
![share track](https://f.cloud.github.com/assets/4105379/587380/afc48f44-c964-11e2-8be7-36fac097b976.png)

**Comment by individual11** [comment]
where are these going? at the top, and have them slide in with a shelf or something?

**Comment by briancrandall** [comment]
Yes, I imagined they would slide down from the top if you mouse north. Still not 100% thrilled with them as a solution. Could we do a share icon, then give the option to share a track or share the whole site from within that dialog box? Is that better?

**Comment by individual11** [comment]
We could, yes, but not sure if that's right either. Less clicks the better.
