### ISSUE TITLE
landing page and unsupported browser pngs

### ISSUE THREAD

**Issue by briancrandall** [individual11/colors#5]
![colorminutes type](https://f.cloud.github.com/assets/4105379/538367/6e4aea0a-c189-11e2-9852-32544e53fb7c.png)

**Comment by briancrandall** [comment]
![colorminutes unsupported](https://f.cloud.github.com/assets/4105379/538368/746f1c9e-c189-11e2-8b6f-1a62e291c126.png)

**Comment by individual11** [comment]
Are these using that special font? If so, I might break them up into seperate pings, but I can do that on my side.

**Comment by briancrandall** [comment]
It's mostly Bodoni now, though some of the punctuation is Times. It's the aliasing I like; not super picky about which face we're using. I feel like that aliasing crudeness is appropriate for someone who uses a butchered Craigslist layout for their own site. Hope it's not trying too hard. That Oh La La font that stays crisp as small sizes with antialiasing turned off isn't in the layouts anymore. I can add back though if you liked it.

**Comment by individual11** [comment]
These aren't working, and not sure why. Let's sit together on monday and make the actual copy work. I think that will be the most consistent across all platforms.

**Comment by briancrandall** [comment]
Is it because they are married to a white background? They might be. I can re-post as isolated type if that helps.

**Comment by individual11** [comment]
We can try it.

**Comment by briancrandall** [comment]
updated pngs!

![colorminutes title](https://f.cloud.github.com/assets/4105379/595689/d52aac44-cb1e-11e2-9d9e-10290ea1ae35.png)
![colorminutes unsupported](https://f.cloud.github.com/assets/4105379/595690/d52d3644-cb1e-11e2-89e7-6f5c8e1ffe26.png)

**Comment by briancrandall** [comment]
The all caps Bodoni type ("Empress of" and "your browser") should be on the same baseline from one page to the next, as should the Italic type ("Colorminutes" and "Unsupported") If they're both centered left to right then that should do it.

**Comment by individual11** [comment]
think it still has the same problem, check it out
