### ISSUE TITLE
Triangle nav PNGs

### ISSUE THREAD

**Issue by briancrandall** [individual11/colors#7]
![nav 01](https://f.cloud.github.com/assets/4105379/581010/4f1878a2-c894-11e2-86de-a8d91b1917f7.png)
![nav 02](https://f.cloud.github.com/assets/4105379/581011/4f180c6e-c894-11e2-8c63-6167ea42b2b5.png)
![nav 03](https://f.cloud.github.com/assets/4105379/581012/4f149548-c894-11e2-9ca2-31d2b11e50d4.png)
![nav 04](https://f.cloud.github.com/assets/4105379/581013/4f21a198-c894-11e2-9374-3029666d20f8.png)
![nav 07](https://f.cloud.github.com/assets/4105379/581014/4f1c946e-c894-11e2-9b72-629efa4098d9.png)
![nav 05](https://f.cloud.github.com/assets/4105379/581015/4f21d528-c894-11e2-903d-a631cc069478.png)
![nav 08](https://f.cloud.github.com/assets/4105379/581016/4f1e5f1a-c894-11e2-9c53-37b1fb21700e.png)
![nav 06](https://f.cloud.github.com/assets/4105379/581017/4f236474-c894-11e2-8c20-2f04d7527c0c.png)
![nav 09](https://f.cloud.github.com/assets/4105379/581018/4f2189b0-c894-11e2-8468-2379adbaef5d.png)
![nav 11](https://f.cloud.github.com/assets/4105379/581019/4f24d4ee-c894-11e2-9f6c-01d7200617e7.png)
![nav 12](https://f.cloud.github.com/assets/4105379/581021/4f2b14da-c894-11e2-9076-acee48d7fd47.png)
![nav 10](https://f.cloud.github.com/assets/4105379/581020/4f2bf508-c894-11e2-9f28-3a8dd626f796.png)
![nav 14](https://f.cloud.github.com/assets/4105379/581022/4f2d8a8a-c894-11e2-9aee-f923a274ced8.png)
![nav 13](https://f.cloud.github.com/assets/4105379/581023/4f291aae-c894-11e2-82b8-a62bc0fb00f8.png)
![nav 15](https://f.cloud.github.com/assets/4105379/581024/4f2b1e58-c894-11e2-8749-f02d81460126.png)

**Comment by individual11** [comment]
We still sliding this in from the sides?

**Comment by briancrandall** [comment]
Think so, yes?

**Comment by individual11** [comment]
Will drop em in and see how it works

**Comment by individual11** [comment]
triangles added, and they look great.. and the transitions, which were accidental look even better.

Need to fix something minor with how the right side pops out earlier than the left (i think it has to do with checking the width to early before going full screen)
